server:
  port: ${APP_PORT:0}

spring:
  datasource:
    url: jdbc:postgresql://${TEST_DB_HOST:localhost}:${TEST_DB_PORT:5432}/${TEST_DB_NAME:bank_rest}
    username: ${TEST_DB_USER:postgres}
    password: ${TEST_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yml

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public


